<html>
<head>
</head>
<body bgcolor="aqua">
	<u1>
  			        <li>PARTE 1:<a href="WHILE.NHILZEEE.PHP" target="contenido"> PRESIONE</a></li>
        			<li>PARTE 2:<a href="IF.NHILZEEE.PHP" target="contenido"> PRESIONE</a></li>
        			<li>PARTE 3:<a href="FOR.NHILZEEEEE.PHP" target="contenido"> PRESIONE</a></li>
        			<li>PARTE 4:<a href="SWITCH.NHILZEEE.PHP" target="contenido"> PRESIONE</a></li>
   </u1>
   </html>